# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['master', 'trunk', 'wip/**']
    # tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:

  Focal-CI:
    runs-on: ubuntu-latest
    steps:
    - run: id
    - run: pwd
    - run: ls -al
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive, github-server-url: 'https://github.com' } }
    - run: git fetch -f --tags		# Fix actions/checkout#290
    - run: git describe --always --long
    - run: pwd
    - run: ls -al
    - run: df -h
    - run: cat /proc/mounts
    - run: cat /proc/cpuinfo
    - name: CI Tests
      run: |
        git describe
        docker images
        du -hsc ~
    - run: |
        git describe | tee git-describe && ls -al
        git -P log -1 --oneline
    - run: false
    - uses: actions/upload-artifact@v4
      with: { name: assets, path: git-describe }

  Ping-IRC:
    if: always()
    needs: [Focal-CI]
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v4.1.1,  with: { fetch-depth: 0 } } # Fix actions/checkout#290
    - run: git fetch -f --tags && git submodule update --init --recursive && git describe --long
    - run: cat "$GITHUB_EVENT_PATH"
    - name: Check Jobs
      run: |
        echo '${{ needs.Focal-CI.result }}'
        [[ ${{ needs.Focal-CI.result }}    =~ success|skipped ]]
    - name: Ping IRC
      if: ${{ always() && !env.ACT }}
      run: |
        .github/workflows/ircbot.py -q -j "#Anklang2" -G -S '${{ job.status }}' "$(git log -1 --format=%s)"
