# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['master', 'trunk', 'wip/**']
    # tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:

  Focal-CI:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/tim-janik/anklang-ci:noble-latest
    steps:
    - run: id
    - run: pwd
    - run: ls -al
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive, github-server-url: 'https://github.com' } }
    - run: git fetch -f --tags		# Fix actions/checkout#290
    - run: git describe --always --long
    - run: docker pull $IMAGE

    - name: Run CI steps inside the container image
      run: |
          # run the same image you used previously inside the VM
          # mount the workspace so files created inside the container are visible to the runner
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            $IMAGE \
            bash -lc "\
              set -euo pipefail; \
              echo 'Inside container:'; \
              pwd; ls -al; \
              df -h; cat /proc/mounts; cat /proc/cpuinfo \
              git describe || true; \
              echo 'Docker images visible inside container:'; docker images || true; \
              du -hsc ~ || true; \
              git describe | tee git-describe || true; \
              ls -al; \
              git -P log -1 --oneline || true \
            "
    - uses: actions/upload-artifact@v4
      with: { name: assets, path: git-describe }

  TestPandoc:
    runs-on: ubuntu-24.04
    steps:
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive, github-server-url: 'https://github.com' } }
    - run: git fetch -f --tags && git describe --long # Fix actions/checkout#290
    - name: Install pandoc
      run: |
        cd /tmp && wget -q -c https://github.com/jgm/pandoc/releases/download/3.7.0.2/pandoc-3.7.0.2-1-amd64.deb
        sudo apt install ./pandoc-3.7.0.2-1-amd64.deb
        pandoc --version
