# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['master', 'trunk', 'wip/**']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:


  Focal-CI:
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:focal-latest', options: '--user 1000:1000' }
    steps:
    - run: id && pwd && env && ls -al
    - run: |
        set -x
        export HOME=$(env -i bash -c 'echo ~') # fix https://github.com/actions/runner/issues/863
        echo HOME="$HOME" | sudo tee -a $GITHUB_ENV # fix the following steps
        sudo chown -R `id -u`:`id -g` .
    - run: id && pwd && env && ls -al
    - run: mkdir cibuild && cd cibuild
    - { uses: actions/checkout@v4.1.1,  with: { fetch-depth: 0 } } # Fix actions/checkout#290
