# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['master', 'trunk', 'wip/**']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:


  Focal-CI:
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:focal-latest' }
    steps:
    - name: 'Setup $HOME and $PWD'
      run: |
        sudo chown -R `id -u`:`id -g` . ~	;# fix $HOME, see actions/runner/issues/863
        export HOME=$(env -i bash -c 'echo ~') && echo HOME=$HOME | sudo tee -a $GITHUB_ENV
        ! [[ $RUNNER_TEMP =~ _ ]] || sudo chmod -R 01777 $RUNNER_TEMP	;# for GH action cache
    - name: 'Git Checkout'
      run: |
        git --version && git clone -q --recurse-submodules https://github.com/$GITHUB_REPOSITORY .
        git fetch origin $GITHUB_REF # e.g. refs/pull/nnn/merge
        [[ $GITHUB_REF =~ ^refs/heads/ ]] && BRANCHORSHA=$GITHUB_REF_NAME || BRANCHORSHA=$GITHUB_SHA
        git checkout -q $BRANCHORSHA && git describe --always && git -P log -1 --oneline
    - run: |
        git describe | tee git-describe && ls -al
    - uses: actions/upload-artifact@v4
      with: { name: assets, path: ./ }
