# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['master', 'trunk', 'wip/**']
    # tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:

  Focal-CI:
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:noble-latest', options: --user runner }
    steps:
    - run: id
    - run: pwd
    - run: ls -al
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive, github-server-url: 'https://github.com' } }
    - run: git fetch -f --tags		# Fix actions/checkout#290
    - run: git describe --always --long
    - run: pwd
    - run: ls -al
    - run: df -h
    - run: cat /proc/mounts
    - run: cat /proc/cpuinfo
    - name: CI Tests
      run: |
        git describe
        docker images
        du -hsc ~
    - run: |
        git describe | tee git-describe && ls -al
        git -P log -1 --oneline
    - uses: actions/upload-artifact@v4
      with: { name: assets, path: git-describe }

  TestPandoc:
    runs-on: ubuntu-24.04
    steps:
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive, github-server-url: 'https://github.com' } }
    - run: git fetch -f --tags && git describe --long # Fix actions/checkout#290
    - name: Install pandoc
      run: |
        cd /tmp && wget -c https://github.com/jgm/pandoc/releases/download/3.7.0.2/pandoc-3.7.0.2-1-amd64.deb && apt install ./pandoc-3.7.0.2-1-amd64.deb
        pandoc --version
