# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['master', 'trunk', 'wip/**']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  Focal-CI:
    runs-on: ubuntu-latest
    env: # INTERACTIVE: docker run -i --cap-add SYS_PTRACE -v $PWD:/anklang ...
      RUN: docker run -v /home/runner/work/gh-testing/gh-testing:/anklang -w /anklang/ -t --rm cifocal
      CITAG: cifocal:latest
    steps:
    # Checkout and fix actions/checkout messing up annotation of the fetched tag: actions/checkout#290
    - uses: actions/checkout@v4
    - run: git fetch --unshallow && git fetch -f --tags

    - run: mkdir -p assets/ && date >assets/a && date >assets/b && date >assets/c
    - uses: actions/upload-artifact@v3
      with: { name: assets, path: assets/ }

    # Use either cache-from or cache-to, so buildx cannot mess up good caches
    - uses: actions/cache@v3
      with:
        key: cifocal-${{hashFiles ('misc/Dockerfile.focal')}}
        path: /tmp/acache
    - name: Docker Build cifocal
      run: |
        docker buildx create --use --driver=docker-container # multi-platform, exports cache, needs --load
        test -r /tmp/acache/index.json && CACHETYPE=--cache-from=type=local,src=/tmp/acache || CACHETYPE=--cache-to=type=local,mode=max,dest=/tmp/acache
        time docker buildx build $CACHETYPE --load -t cifocal:latest -f misc/Dockerfile.focal misc

    - name: CI Tests
      run: |
        git describe
        docker images
        ls -al /tmp/
        du -hsc /tmp/ || true
        du -hsc ~
        $RUN sudo chown ubuntu:ubuntu -R /anklang/   # Fix $UID (gh-runner $UID != 1000)
        $RUN git describe
        $RUN sudo chown `id -u`:`id -g` -R /anklang/ # Cleanup $UID
